name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          output_action: none
          token: ${{ secrets.GITHUB_TOKEN }}
          user: LingmoOS
          config_order: base
          config_timezone: Asia/Shanghai
          base: header, activity, community, repositories
          base_indepth: yes
          repositories_skipped: Lingmo-OS, kernel, linux-kernel-6.8.7, lingmo-linux-kernel-6.8.4, lingmo-grub2, libx11, lingmo-wine, LingmoOS, lingmo-community, lingmo-system-build, pacman, rpm, libsolv, kdeconnect-android, kdeconnect-kde, kdeconnect-meta, extra-cmake-modules, dnf, libdnf, lpm, linux-kernel
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_details: percentage, bytes-size, lines
          plugin_followup: yes
      - uses: actions/upload-artifact@v4
        with:
          path: metrics_renders/metrics.svg
    
  deploy:
    needs: github-metrics
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: metrics.svg
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
